---
title: "Climbing + Climate Change"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    theme: lumen
runtime: shiny
---

```{r setup, include=FALSE}

# Load required packages
library(tidyverse)
library(ggridges)
library(plotly)
library(viridis)
library(hrbrthemes)
library(formattable)

# Read in data and create factor levels for the months column
load("all_locations.rda")

# List of all possible locations
locations_list <- locations$Place

```

# Sidebar {.sidebar}

```{r inputs}

selectInput('location',
            label = 'Location:',
            choices = locations_list,
            selected = "The Buttermilks")

selectInput('scenario',
            label = 'Scenario:',
            choices = c("Low Emissions",
                        "High Emissions"),
            selected = "High Emissions")

sliderInput("years", "Time Range:",
            min = 2020, max = 2100,
            value = c(2035, 2065),
            dragRange = TRUE,
            step = 5,
            sep = "")

sliderInput("temps", "Temperature Range:",
            min = 20, max = 100,
            value = c(35, 55),
            dragRange = TRUE,
            post = " F",
            sep = "")

```

```{r reactive df}

# Using lapply to run through all 8 slugs and generate an ensemble mean for all priority models
# Takes about 10-15 seconds per location

rctv_df <- reactive({
  
  reactive_df <- all_locations %>%
    filter(Place == input$location,
           Year %in% (input$years[1]:input$years[2]))
  
})

```



# Ridge Plots

```{r ridge plots}

# Still need to make the year an average of the range
# Using 2050 for now to test it out

output$ridge_plot <- renderPlot({
  
  ridge_graph(data = rctv_df(),
              scenario = input$scenario,
              maxT = input$temps[2],
              minT = input$temps[1])
  
})

plotOutput('ridge_plot')

```


# Trends 

```{r trends}

# Trend plot only takes in location and ideal temps

output$points <- renderPlotly({
  
  plot <- all_locations %>%
  filter(Place == input$location) %>%
  mutate(InRange = case_when(
    Value >= input$temps[1] & Value <= input$temps[2] ~ 1,
    TRUE ~ 0
  )) %>%
  group_by(Year, Scenario) %>%
  summarize(Days = round(sum(InRange), digits = 2)) %>%
  as.data.frame() %>%
  ggplot(aes(x = as.numeric(Year), y = Days, color = Scenario)) +
  geom_smooth() +
  geom_point(size = 1.5, alpha = .9) +
  scale_color_manual(labels = c("Points, Low Emissions", "Points, High Emissions"),
                     values = c("#de5f5f", "#74a1e8")) +
  theme_ipsum() +
  scale_x_continuous(breaks = seq(from = 2020, to = 2100, by = 10), limits = c(2020, 2100)) +
  labs(x = "",
       y = "Ideal Days",
       title = paste0("Annual Ideal Climbing Days per Year in ", input$location))

  ggplotly(plot)
  
})

plotlyOutput('points')

```


# Distribution Plots

```{r}

selectInput('multiL',
            label = 'Locations:',
            choices = locations_list,
            selected = c("The Buttermilks", "Yosemite"),
            multiple = TRUE)

selectInput('multiS',
            label = 'Scenarios:',
            choices = c("High Emissions", "Low Emissions"),
            selected = c("High Emissions", "Low Emissions"),
            multiple = TRUE)

```

## Output

```{r}

# Add radio buttons for selecting different locations?
# Distribution plots by place

output$dist <- renderPlot({
  
  all_locations %>%
    filter(Year %in% (input$years[1]:input$years[2]),
           Scenario %in% input$multiS,
           Place %in% input$multiL) %>%
    ggplot(aes(x = Value, fill = Scenario)) + 
    geom_density(alpha = 0.6) +
    facet_wrap(~Place) +
    theme_ipsum() +
    scale_fill_brewer(palette = "Set2") +
    labs(x = "Daily Maximum Temperature [F]",
         y = "Density",
         fill = "",
         title="Distribution of daily maximum temperature",
         subtitle="by climbing location") +
    theme(plot.title = element_text(size = 16),
          legend.position = "bottom",
          plot.background = element_rect(fill = "#ffffff", color = NA)) +
    geom_vline(xintercept = input$temps[2], linetype = 2, color = "darkblue") +
    geom_vline(xintercept = input$temps[1], linetype = 2, color = "darkblue") +
    annotate("rect", xmin = input$temps[1], xmax = input$temps[2], ymin = 0, 
             fill = "blue", ymax = .035, alpha = 0.1) 
  
})

plotOutput('dist', width = "100%", height = "550px")

```


# Test 

## Table 

```{r}

renderTable({
  head(rctv_df())
})

```

## Text

```{r test}

output$values <- renderText({

  paste("The starting year is", input$years[1],
        "and the ending year is", input$years[2],
        "and the total range is", input$years[2]-input$years[1], ".",
        "The selected emissions scenario is", input$scenario, ".",
        "The ideal maximum daily temperature range is", input$temps[1], "to", input$temps[2], ".")

})

textOutput('values')

```
